import type { LinkItem } from "@/types/link";

export const mockUser = {
  email: "student@example.com",
  name: "링크박스 사용자",
};

export const mockCategories = [
  "문서",
  "튜토리얼",
  "레퍼런스",
  "블로그",
  "영상",
  "강의",
];

export const mockTags = [
  "react",
  "typescript",
  "javascript",
  "css",
  "nodejs",
  "frontend",
  "backend",
  "performance",
  "best-practices",
];

export const mockLinks: LinkItem[] = [
  {
    id: "1",
    user_id: "mock-user",
    title: "React 공식 문서 - Hooks",
    url: "https://react.dev/reference/react",
    description: "useState, useEffect 등 React Hook을 확인하기 위한 공식 문서",
    category: "문서",
    tags: ["react", "hooks", "frontend"],
    status: "completed",
    priority: "high",
    is_favorite: true,
    created_at: "2026-05-10T10:30:00Z",
    updated_at: "2026-05-10T10:30:00Z",
  },
  {
    id: "2",
    user_id: "mock-user",
    title: "TypeScript Deep Dive",
    url: "https://basarat.gitbook.io/typescript",
    description: "고급 패턴까지 다루는 TypeScript 종합 가이드",
    category: "튜토리얼",
    tags: ["typescript", "programming"],
    status: "reading",
    priority: "high",
    is_favorite: true,
    created_at: "2026-05-09T14:20:00Z",
    updated_at: "2026-05-09T14:20:00Z",
  },
  {
    id: "3",
    user_id: "mock-user",
    title: "Tailwind CSS 공식 문서",
    url: "https://tailwindcss.com/docs",
    description: "유틸리티 우선 CSS 프레임워크 레퍼런스",
    category: "문서",
    tags: ["css", "tailwind", "styling"],
    status: "unread",
    priority: "medium",
    is_favorite: false,
    created_at: "2026-05-08T09:15:00Z",
    updated_at: "2026-05-08T09:15:00Z",
  },
  {
    id: "4",
    user_id: "mock-user",
    title: "Web.dev 성능 가이드",
    url: "https://web.dev/performance",
    description: "웹 성능 최적화를 위한 모범 사례 정리",
    category: "튜토리얼",
    tags: ["performance", "web", "optimization"],
    status: "unread",
    priority: "medium",
    is_favorite: false,
    created_at: "2026-05-07T16:45:00Z",
    updated_at: "2026-05-07T16:45:00Z",
  },
  {
    id: "5",
    user_id: "mock-user",
    title: "CSS Tricks - Flexbox 가이드",
    url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox",
    description: "CSS Flexbox 레이아웃을 정리한 실전 가이드",
    category: "튜토리얼",
    tags: ["css", "layout", "flexbox"],
    status: "completed",
    priority: "low",
    is_favorite: false,
    created_at: "2026-05-06T11:00:00Z",
    updated_at: "2026-05-06T11:00:00Z",
  },
  {
    id: "6",
    user_id: "mock-user",
    title: "Node.js Best Practices",
    url: "https://github.com/goldbergyoni/nodebestpractices",
    description: "Node.js 모범 사례와 패턴을 정리한 종합 레퍼런스",
    category: "레퍼런스",
    tags: ["nodejs", "backend", "best-practices"],
    status: "reading",
    priority: "high",
    is_favorite: true,
    created_at: "2026-05-05T13:30:00Z",
    updated_at: "2026-05-05T13:30:00Z",
  },
];
