import type { LinkItem } from "@/types/link";

export const mockUser = {
  email: "student@example.com",
  name: "LinkBox User",
};

export const mockCategories = [
  "Documentation",
  "Tutorial",
  "Reference",
  "Blog Post",
  "Video",
  "Course",
];

export const mockTags = [
  "react",
  "typescript",
  "javascript",
  "css",
  "nodejs",
  "frontend",
  "backend",
  "performance",
  "best-practices",
];

export const mockLinks: LinkItem[] = [
  {
    id: "1",
    user_id: "mock-user",
    title: "React Documentation - Hooks",
    url: "https://react.dev/reference/react",
    description: "Reference for useState, useEffect, and other React hooks",
    category: "Documentation",
    tags: ["react", "hooks", "frontend"],
    status: "completed",
    priority: "high",
    is_favorite: true,
    created_at: "2026-05-10T10:30:00Z",
    updated_at: "2026-05-10T10:30:00Z",
  },
  {
    id: "2",
    user_id: "mock-user",
    title: "TypeScript Deep Dive",
    url: "https://basarat.gitbook.io/typescript",
    description: "Comprehensive TypeScript guide covering advanced patterns",
    category: "Tutorial",
    tags: ["typescript", "programming"],
    status: "reading",
    priority: "high",
    is_favorite: true,
    created_at: "2026-05-09T14:20:00Z",
    updated_at: "2026-05-09T14:20:00Z",
  },
  {
    id: "3",
    user_id: "mock-user",
    title: "Tailwind CSS Documentation",
    url: "https://tailwindcss.com/docs",
    description: "Utility-first CSS framework reference",
    category: "Documentation",
    tags: ["css", "tailwind", "styling"],
    status: "unread",
    priority: "medium",
    is_favorite: false,
    created_at: "2026-05-08T09:15:00Z",
    updated_at: "2026-05-08T09:15:00Z",
  },
  {
    id: "4",
    user_id: "mock-user",
    title: "Web.dev Performance Guide",
    url: "https://web.dev/performance",
    description: "Best practices for web performance optimization",
    category: "Tutorial",
    tags: ["performance", "web", "optimization"],
    status: "unread",
    priority: "medium",
    is_favorite: false,
    created_at: "2026-05-07T16:45:00Z",
    updated_at: "2026-05-07T16:45:00Z",
  },
  {
    id: "5",
    user_id: "mock-user",
    title: "CSS Tricks - Flexbox Guide",
    url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox",
    description: "Complete guide to CSS Flexbox layout",
    category: "Tutorial",
    tags: ["css", "layout", "flexbox"],
    status: "completed",
    priority: "low",
    is_favorite: false,
    created_at: "2026-05-06T11:00:00Z",
    updated_at: "2026-05-06T11:00:00Z",
  },
  {
    id: "6",
    user_id: "mock-user",
    title: "Node.js Best Practices",
    url: "https://github.com/goldbergyoni/nodebestpractices",
    description: "Comprehensive guide to Node.js best practices and patterns",
    category: "Reference",
    tags: ["nodejs", "backend", "best-practices"],
    status: "reading",
    priority: "high",
    is_favorite: true,
    created_at: "2026-05-05T13:30:00Z",
    updated_at: "2026-05-05T13:30:00Z",
  },
];
